export const BLOG_POST_REQUEST = 'BLOG_POST_REQUEST'
export const BLOG_POST_SUCCESS = 'BLOG_POST_SUCCESS'
export const BLOG_POST_FAIL = 'BLOG_POST_FAIL'

export const BLOG_POST_DETAILS_REQUEST = 'BLOG_POST_DETAILS_REQUEST'
export const BLOG_POST_DETAILS_SUCCESS = 'BLOG_POST_DETAILS_SUCCESS'
export const BLOG_POST_DETAILS_FAIL = 'BLOG_POST_DETAILS_FAIL'